---
docker_fedora_repo_name: "docker-ce-stable"
docker_fedora_repo_description: "Docker CE Stable - $basearch"
docker_fedora_repo_url: "https://download.docker.com/linux/fedora/$releasever/$basearch/stable"
docker_fedora_repo_validate_certs: true
docker_fedora_repo_gpg_check: true
docker_fedora_repo_gpg_key: "https://download.docker.com/linux/fedora/gpg"

docker_fedora_cli_package: "docker-ce-cli"
docker_fedora_plugin_buildx_package: "docker-buildx-plugin"
docker_fedora_plugin_compose_package: "docker-compose-plugin"
docker_fedora_base_packages:
  - "docker-ce"
  - "docker-ce-cli"
  - "containerd.io"
docker_fedora_packages: >-2
  {{
    docker_fedora_base_packages
    + (docker_plugin_buildx_enable | default(false)
      | ternary([ docker_fedora_plugin_buildx_package ], []))
    + (docker_plugin_compose_enable | default(false)
      | ternary([ docker_fedora_plugin_compose_package ], []))
  }}
docker_fedora_legacy_packages:
  - "docker"
  - "docker-client"
  - "docker-client-latest"
  - "docker-common"
  - "docker-latest"
  - "docker-latest-logrotate"
  - "docker-logrotate"
  - "docker-selinux"
  - "docker-engine-selinux"
  - "docker-engine"
