namespace: finallycoffee
name: base
version: 0.2.1
readme: README.md
authors:
- transcaffeine <transcaffeine@finally.coffee>
description: Roles for base services which are common dependencies other services like databases
dependencies:
  "community.docker": "^4.2.0"
license_file: LICENSE.md
build_ignore:
- '*.tar.gz'
repository: https://git.finally.coffee/finallycoffee/base
issues: https://codeberg.org/finallycoffee/ansible-collection-base/issues
tags:
  - docker
  - lego
  - minio
  - nginx
  - restic
  - docker
