namespace: finallycoffee
name: base
version: 0.3.0
readme: README.md
authors:
- transcaffeine <transcaffeine@finally.coffee>
description: >-2
  Roles for base services which are core functionality like managing packages
  and ssh or common dependencies other services like databases
dependencies:
  "community.docker": "^4.2.0"
  "community.general": "^10.0.0"
license_file: LICENSE.md
build_ignore:
- '*.tar.gz'
repository: https://git.finally.coffee/finallycoffee/base
issues: https://codeberg.org/finallycoffee/ansible-collection-base/issues
tags:
  - bootstrap
  - ssh
  - mosh
  - docker
  - lego
  - minio
  - nginx
  - restic
  - user_management
  - openldap
