---
docker_systemd_service_name: "docker.service"
docker_systemd_service_state: >-2
  {{ (docker_state == 'present') | ternary('started', 'stopped') }}
docker_systemd_service_enabled: "{{ (docker_state == 'present') }}"
