---
- name: Ensure sshd is reloaded
  ansible.builtin.systemd_service:
    name: "{{ openssh_sshd_systemd_service_name }}"
    state: "reloaded"
  when: ansible_facts['service_mgr'] == 'systemd'
  listen: openssh_sshd_reload
