---
- name: Ensure openssh server package is {{ openssh_state }} (dnf)
  ansible.builtin.dnf:
    name: "{{ openssh_packages[_ansible_distribution] }}"
    state: "{{ openssh_state }}"
  when:
    - _ansible_pkg_mgr in ['dnf', 'dnf5']
    - _ansible_distribution in openssh_packages.keys()

- name: Ensure openssh server package is {{ openssh_state }} (apt)
  ansible.builtin.apt:
    package: "{{ openssh_packages[_ansible_distribution] }}"
    state: "{{ openssh_state }}"
  when:
    - _ansible_pkg_mgr in ['apt']
    - _ansible_distribution in openssh_packages.keys()
