---
- name: Ensure 'minio_state' is valid
  ansible.builtin.fail:
    msg: >-
      Unsupported state '{{ minio_state }}'!
      Supported states are {{ minio_states | join(', ') }}.
  when: minio_state not in minio_states

- name: Ensure 'minio_deployment_method' is valid
  ansible.builtin.fail:
    msg: >-
      Unsupported state '{{ minio_deployment_method }}'!
      Supported states are {{ minio_deployment_methods | join(', ') }}.
  when: minio_deployment_method not in minio_deployment_methods

- name: Ensure minio run user is {{ minio_state }}
  ansible.builtin.user:
    name: "{{ minio_user }}"
    state: "{{ minio_state }}"
    system: true
  when: minio_create_user

- name: Deploy minio using {{ minio_deployment_method }}
  ansible.builtin.include_tasks:
    file: "deploy-{{ minio_deployment_method }}.yml"
