---
- name: Ensure config directory '{{ docker_daemon_config_file | dirname }}' is present
  ansible.builtin.file:
    path: "{{ docker_daemon_config_file | dirname }}"
    state: "directory"
    mode: "0755"
    owner: "{{ docker_daemon_config_owner }}"
    group: "{{ docker_daemon_config_group }}"

- name: Configure docker daemon using '{{ docker_daemon_config_file }}'
  ansible.builtin.copy:
    content: "{{ docker_daemon_config | to_json }}"
    dest: "{{ docker_daemon_config_file }}"
    mode: "{{ docker_daemon_config_file_mode }}"
    owner: "{{ docker_daemon_config_owner }}"
    group: "{{ docker_daemon_config_group }}"
  when: docker_daemon_config | string | length > 0
  notify: docker-restart
