---
- name: Ensure legacy docker packages are removed
  ansible.builtin.dnf:
    name: "{{ docker_rhel_legacy_packages }}"
    state: absent
  when: docker_remove_legacy_packages

- name: Add dnf repository for docker
  ansible.builtin.yum_repository:
    name: "{{ docker_rhel_repo_name }}"
    description: "{{ docker_rhel_repo_description }}"
    baseurl: "{{ docker_rhel_repo_url }}"
    validate_certs: "{{ docker_rhel_repo_validate_certs }}"
    gpgkey: "{{ docker_rhel_repo_gpg_key }}"
    gpgcheck: "{{ docker_rhel_repo_gpg_check }}"
    state: "{{ docker_state }}"

- name: Install dnf packages for docker
  ansible.builtin.dnf:
    name: "{{ docker_rhel_packages }}"
    state: "{{ docker_state }}"
